version: '2.3'
services:
  #camera:
  #  image: node:8.15-alpine
  #  volumes:
  #   - ./camera/webservice:/root/webservice:rw
  #  environment:
  #   - VIRTUAL_HOST=camera.thesis.leoregner.eu
  #  expose:
  #   - "80"
  #  command: sh -c "cd /root/webservice && npm install -y && node index.js"
  #  restart: always
  #r2n2:
  #  build: ./r2n2/
  #  runtime: nvidia
  #  environment:
  #   - VIRTUAL_HOST=r2n2.thesis.leoregner.eu
  #  restart: always
  #omarpadierna:
  #  build: ./omarpadierna/
  #  environment:
  #   - VIRTUAL_HOST=omarpadierna.thesis.leoregner.eu
  #  restart: always
  #cloudcompare:
  #  build: ./cloudcompare/
  #  environment:
  #   - VIRTUAL_HOST=cloudcompare.thesis.leoregner.eu
  #  restart: always
  realsense:
    build: ./realsense/
    environment:
     - VIRTUAL_HOST=realsense.thesis.leoregner.eu
    privileged: true # share physical devices with container
    restart: always
  pcl:
    build: ./pcl/
    environment:
     - VIRTUAL_HOST=pcl.thesis.leoregner.eu
    restart: always
  coordsmapping:
     build: ./coordsmapping/
     environment:
      - VIRTUAL_HOST=coordsmapping.thesis.leoregner.eu
     restart: always
  robot:
      build: ./robot/
      environment:
       - VIRTUAL_HOST=robot.thesis.leoregner.eu
      restart: always
  processengine:
    image: nginx
    volumes:
     - ./processengine:/usr/share/nginx/html:rw
    environment:
     - VIRTUAL_HOST=processengine.thesis.leoregner.eu
    restart: always
  reverseproxy:
    image: jwilder/nginx-proxy
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
     - ./reverseproxy/conf/proxy-settings.conf:/etc/nginx/conf.d/proxy-settings.conf:rw
     - ./reverseproxy/conf/error-pages.conf:/etc/nginx/conf.d/error-pages.conf:rw
     - ./reverseproxy/html:/usr/share/nginx/html:rw
    ports:
     - "80:80"
    restart: always
