version: '2.3'
services:
  realsense:
    build: ./realsense/
    ports:
     - "8081:8081"
    privileged: true # share physical devices with container
    restart: always
  pcl:
    build: ./pcl/
    ports:
     - "8082:8082"
    restart: always
  coordsmapping:
     build: ./coordsmapping/
     ports:
      - "8083:8083"
     restart: always
  robot:
      build: ./robot/
      ports:
       - "8084:8084"
      restart: always
  processengine:
    image: nginx
    volumes:
     - ./processengine:/usr/share/nginx/html:rw
    environment:
     - VIRTUAL_HOST=processengine.localhost
    restart: always
  reverseproxy:
    image: jwilder/nginx-proxy
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
     - ./reverseproxy/conf/proxy-settings.conf:/etc/nginx/conf.d/proxy-settings.conf:rw
     - ./reverseproxy/conf/error-pages.conf:/etc/nginx/conf.d/error-pages.conf:rw
     - ./reverseproxy/html:/usr/share/nginx/html:rw
    ports:
     - "80:80"
    restart: always
