version: '2.3'
services:
  r2n2:
    build: ./r2n2/
    runtime: nvidia
  cloudcompare:
    build: ./cloudcompare/
    privileged: True
  processengine:
    image: nginx
    volumes:
     - ./processengine:/usr/share/nginx/html:ro