version: '2.3'
services:
  camera:
    image: node:8.15-alpine
    volumes:
     - ./camera/webservice:/root/webservice:rw
    enviroment:
     - VIRTUAL_HOST=camera.thesis.leoregner.eu
    command: bash -c "cd /root/webservice && npm install -y && node index.js"
  r2n2:
    build: ./r2n2/
    runtime: nvidia
    environment:
     - VIRTUAL_HOST=r2n2.thesis.leoregner.eu
  cloudcompare:
    build: ./cloudcompare/
    privileged: True
    environment:
     - VIRTUAL_HOST=cloudcompare.thesis.leoregner.eu
  processengine:
    image: nginx
    volumes:
     - ./processengine:/usr/share/nginx/html:rw
    environment:
     - VIRTUAL_HOST=processengine.thesis.leoregner.eu
  reverseproxy:
    image: jwilder/nginx-proxy
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
     - ./reverseproxy/conf/proxy-settings.conf:/etc/nginx/conf.d/proxy-settings.conf:rw
     - ./reverseproxy/conf/error-pages.conf:/etc/nginx/conf.d/error-pages.conf:rw
     - ./reverseproxy/html:/usr/share/nginx/html:rw
    ports:
     - "80:80"