version: '2.3'
services:
  r2n2:
    build: ./r2n2/
    runtime: nvidia
    networks:
     - reverseproxynet
  environment:
     - VIRTUAL_HOST=r2n2.thesis.leoregner.eu
  cloudcompare:
    build: ./cloudcompare/
    privileged: True
    networks:
     - reverseproxynet
    environment:
     - VIRTUAL_HOST=cloudcompare.thesis.leoregner.eu
  processengine:
    image: nginx
    volumes:
     - ./processengine:/usr/share/nginx/html:ro
    networks:
     - reverseproxynet
    environment:
     - VIRTUAL_HOST=processengine.thesis.leoregner.eu
  reverseproxy:
    image: jwilder/nginx-proxy
    ports:
     - "80:80"
    networks:
     - reverseproxynet
networks:
    reverseproxynet:
        driver: bridge