version: '2.3'
services:
  r2n2:
    build: ./r2n2/
    runtime: nvidia
    environment:
     - VIRTUAL_HOST=r2n2.thesis.leoregner.eu
  cloudcompare:
    build: ./cloudcompare/
    privileged: True
    environment:
     - VIRTUAL_HOST=cloudcompare.thesis.leoregner.eu
  processengine:
    image: nginx
    volumes:
     - ./processengine:/usr/share/nginx/www:rw
    environment:
     - VIRTUAL_HOST=processengine.thesis.leoregner.eu
  reverseproxy:
    image: jwilder/nginx-proxy
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
     - ./reverseproxy:/etc/nginx/conf.d:rw
    ports:
     - "80:80"